// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProxyPeeker.Storage;

#nullable disable

namespace ProxyPeeker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProxyPeeker.Storage.RequestEntity", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"));

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_url");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_body");

                    b.Property<string>("ResponseStatusCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_status_code");

                    b.Property<DateTime?>("SendAt")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("send_at");

                    b.HasKey("Id");

                    b.ToTable("request", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
